site_name: IndieLibrary
theme:
  font:
    text: Merriweather Sans
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: lime

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: purple
      accent: deep orange
