nav:
  - Home: index.md
  - Menu Reimagined: MenuReimagined
  - Yggdrasil: Yggdrasil
  - More Resources: Util
  #  - "*"
  - Extras:
    - Blog: Blog/index.md
    - Posts: Blog/posts
    
not_in_nav:
flatten_single_child_sections: true
# append_unmatched: true